logging:
  file:
    name: app.log

encryption:
  key: 45678845367465764582145678974131
server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:''}
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  data:
    redis:
      host: redis-10521.c239.us-east-1-2.ec2.redns.redis-cloud.com
      port: 10521
      password: vbQOUQdABZEwJKF151bPV5bxL3Klqu7f
